### ISSUE TITLE
Broken link on Wiki

### ISSUE THREAD

**Issue by 71FuDD** [Ultramarine-Linux/wiki-new#11]
Using firefox browser, version 113.0.2

Go to:
https://wiki.ultramarine-linux.org/en/development/developing-for-ultramarine/

On the following line click the link:

To build packages for Ultramarine, see Using Andaman.

The link takes you to the following URL:

https://wiki.ultramarine-linux.org/development/anda

This gives a 404 File not found error.

NB: I initially filed this under Website in error, apologies.

**Comment by trobonox** [comment]
Thanks for pointing this out, it should be fixed now. 
Also please keep in mind that the wiki is a little outdated and needs to be updated with new info.
