### ISSUE TITLE
`shell.mdx` missing instrictuons on how to use important commands commands.

### ISSUE THREAD

**Issue by VehementHam** [Ultramarine-Linux/wiki-new#26]
https://wiki.ultramarine-linux.org/en/linux/shell/ is missing instructions for the `cp`, `ln` and `ls` commands. It is also worth mentioning the `ln` command and the `ls` command. 

For `cp` mention the `-r` flag as well. 

For `ln`, mention how simlinks are relative, and provide an axample for `ln -s`. There is no need to mention hard links.

For `ls`, mention the `-a` flag and `-l` flags. 

These are all critical to using the command line. Much more so than `touch`, which is mentioned.

**Comment by nothingneko** [comment]
Hi, thanks for the feedback! We didn't really touch this page in our big docs rewrite, it's good to see some eyes on it. I'll get to these changes soon (unless you'd like to write and PR them yourself of course :3)

**Comment by VehementHam** [comment]
Of course it goes without saying that too much information can be a bad thing.

**Comment by VehementHam** [comment]
#31

**Comment by VehementHam** [comment]
#31 I will add instructions for the `cp` command later.
