### ISSUE TITLE
Auto Login not working

### ISSUE THREAD

**Issue by Hidroxyde** [Ultramarine-Linux/wiki-new#3]
The option for autologin on the user's configuration page is not working.
The toggle stays on until you leave the page.
Was attempted on an administrator and a regular user.
Forgot to mention that i'm using the budgie version.

**Comment by trobonox** [comment]
This is a known issue related to Budgie and LightDM. I am currently investigating its cause and thinking about how this issue could be solved internally. (We are currently working on a settings/tweaks app, so we could integrate a working version into that in the future)

As a temporary workaround, you can install the package `lightdm-settings` using dnf, start it from the terminal using `sudo lightdm-settings` and configure autologin there (can be found in the second tab).
Please let me know if that worked and if you need any further assistance!


---------

Also a quick heads up for the future: this repository is related to our wiki page, so the issues here should only be used if you find something like a typo, bug, or want to suggest an addition. 

Next time when you require support or want to report a general bug like this, please open an issue in the main repo that can be found here: https://github.com/Ultramarine-Linux/ultramarine
Alternatively, you can also join our Discord server which is linked on the official website.

It would be extremely helpful, as it makes it easier for our small team to keep track of all the issues and where they belong to.

**Comment by korewaChino** [comment]
Closing this issue as this is invalid. Please repost on the main repo.
